### ISSUE TITLE
 nuxt build --analyse fail

### ISSUE THREAD

**Issue by yann-yinn** [pi0/nuxt-starter-pwa#4]
Hello ! using pwa module, "**nuxt build -a**" fails and shows

>  nuxt build -a
> [nuxt] Building...
> [nuxt] Unable to resolve module @nuxtjs/pwa
> { Error: Cannot find module '@nuxtjs/pwa'

Maybe a nuxt.js issue ?

**Comment by pi0** [comment]
Hi. Thanks for the report. Will investigate it soon with latest `dev` branch. Any more information on this would be awesome. Also please check you have installed `alpha.4` (by checking node_modules/nuxt/package.json) former releases had similar problems.

**Comment by yann-yinn** [comment]
nuxt version : 1.0.0-alpha.4
nuxtjs/pwa version : 0.2.0

**Comment by pi0** [comment]
@nyl-auster I've checked that. Seems this problem only happens when directly calling nuxt (It is working when using scripts of `package.json`) You can currently use something like this `yarn build -- -a`  And oops you are also using depricated  template!! Please switch to https://github.com/nuxt-community/pwa-template :)
